#!/usr/bin/env python

from __future__ import print_function

import os
import sys
import subprocess
import functools


shell = functools.partial(subprocess.call, shell=True)


def django_environ(testing=False):

    def decorator(func):

        settings_module = 'sampleproject.settings'

        def setup_environ():
            sys.path.insert(0, 'sampleproject')
            os.environ['DJANGO_SETTINGS_MODULE'] = settings_module
            print('Using settings: {0}'.format(settings_module))

        def create_database():
            import django
            MINOR = django.VERSION[1]
            if MINOR >= 7:
                django.setup()

            from django.core.management import call_command
            from django.contrib.auth.models import User

            if MINOR >= 7:
                call_command('migrate', interactive=False)
            else:
                call_command('syncdb', interactive=False)

            admin, created = User.objects.get_or_create(
                username='admin',
                is_staff=True,
                is_superuser=True
            )
            if created:
                admin.set_password('admin')
                admin.save()

            print('Superuser created. Login "admin" password "admin"')

        @functools.wraps(func)
        def wrapper(*args, **kw):
            cleanup()
            setup_environ()
            create_database()
            return func(*args, **kw)

        return wrapper

    return decorator

@django_environ()
def serve(argv):
    '''Start django development server'''
    from django.core.management import execute_from_command_line
    execute_from_command_line(['manage.py', 'runserver'])


def cleanup(*args):
    '''Removes temporary files'''
    shell('find . -name *.pyc -delete')
    shell('find . -name __pycache__ -delete')
    shell('find . -name db_test.sqlite -delete')

def pypi(*args):
    '''Upload to pypi'''
    shell('python setup.py sdist upload')

def help(*args):
    '''Show help message and exit'''
    print('Available tasks: \n')
    for task in tasks:
        print(' - {0}: {1}'.format(task.__name__, task.__doc__), file=sys.stderr)
    print()

tasks = serve, cleanup, pypi, help

if __name__ == '__main__':
    try:
        globals()[sys.argv[1]](sys.argv[2:])
    except (IndexError, KeyError):
        help()
        sys.exit(1)
