name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
  
    env:
      working-directory: ./sampleproject

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]
        django-version: [2.2, 3.1, 3.2]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      working-directory: ${{ env.working-directory }}
      run: |
        python -m pip install --upgrade pip
        pip install django~=${{ matrix.django-version }}.0ì
        pip install -r test-requirements.txt
    - name: Run Tests
      working-directory: ${{ env.working-directory }}
      run: |
        python manage.py test
